package com.mohdiop.m3fundapi.entity.enums;

public enum UserRole {
    ROLE_PROJECT_OWNER,
    ROLE_CONTRIBUTOR,
    ROLE_DONATOR,
    ROLE_INVESTOR,
    ROLE_VOLUNTEER,
    ROLE_SUPER_ADMIN,
    ROLE_VALIDATIONS_ADMIN,
    ROLE_PAYMENTS_ADMIN,
    ROLE_USERS_ADMIN,
    ROLE_SYSTEM
}
